import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Container, Col, Row } from 'react-bootstrap'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import Feature from '@/components/Feature'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Kelompok 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          {/* Section Navbar */}
          {/* Call Navbar */}
          <Navbar></Navbar>
        <Container>
          <br /><br />
          {/* Section Hero */}
          <Hero></Hero>
          <br /><br />
          <Feature></Feature>
          <br /><br />
        </Container>
      </main>
      <Footer></Footer>
    </>
  )
}
